/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DevStatesRouteImport } from './routes/dev/states'
import { Route as DevSwipeRouteImport } from './routes/dev/swipe'
import { Route as RoomsCodeRouteImport } from './routes/rooms/$code'
import { Route as ApiRoomsCodeRouteImport } from './routes/api/rooms/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DevStatesRoute = DevStatesRouteImport.update({
  id: '/dev/states',
  path: '/dev/states',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSwipeRoute = DevSwipeRouteImport.update({
  id: '/dev/swipe',
  path: '/dev/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsCodeRoute = RoomsCodeRouteImport.update({
  id: '/rooms/$code',
  path: '/rooms/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsCodeRoute = ApiRoomsCodeRouteImport.update({
  id: '/api/rooms/$code',
  path: '/api/rooms/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/playground': typeof PlaygroundRoute
  '/dev/states': typeof DevStatesRoute
  '/dev/swipe': typeof DevSwipeRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/api/rooms/$code': typeof ApiRoomsCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/playground': typeof PlaygroundRoute
  '/dev/states': typeof DevStatesRoute
  '/dev/swipe': typeof DevSwipeRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/api/rooms/$code': typeof ApiRoomsCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/playground': typeof PlaygroundRoute
  '/dev/states': typeof DevStatesRoute
  '/dev/swipe': typeof DevSwipeRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/api/rooms/$code': typeof ApiRoomsCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/playground'
    | '/dev/states'
    | '/dev/swipe'
    | '/rooms/$code'
    | '/api/rooms/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/playground'
    | '/dev/states'
    | '/dev/swipe'
    | '/rooms/$code'
    | '/api/rooms/$code'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/playground'
    | '/dev/states'
    | '/dev/swipe'
    | '/rooms/$code'
    | '/api/rooms/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  PlaygroundRoute: typeof PlaygroundRoute
  DevStatesRoute: typeof DevStatesRoute
  DevSwipeRoute: typeof DevSwipeRoute
  RoomsCodeRoute: typeof RoomsCodeRoute
  ApiRoomsCodeRoute: typeof ApiRoomsCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/states': {
      id: '/dev/states'
      path: '/dev/states'
      fullPath: '/dev/states'
      preLoaderRoute: typeof DevStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/swipe': {
      id: '/dev/swipe'
      path: '/dev/swipe'
      fullPath: '/dev/swipe'
      preLoaderRoute: typeof DevSwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$code': {
      id: '/rooms/$code'
      path: '/rooms/$code'
      fullPath: '/rooms/$code'
      preLoaderRoute: typeof RoomsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$code': {
      id: '/api/rooms/$code'
      path: '/api/rooms/$code'
      fullPath: '/api/rooms/$code'
      preLoaderRoute: typeof ApiRoomsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  PlaygroundRoute: PlaygroundRoute,
  DevStatesRoute: DevStatesRoute,
  DevSwipeRoute: DevSwipeRoute,
  RoomsCodeRoute: RoomsCodeRoute,
  ApiRoomsCodeRoute: ApiRoomsCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
